export interface ParseConclusion {
  person?: string;
  number?: string;
  gender?: string;
  tense?: string;
  stem?: string;
  verbClass?: string;
  root?: string;
}

export interface HighlightRange {
  start: number;
  end: number;
  type: 'match' | 'root' | 'affix';
  label?: string;
}

export interface ParsingRule {
  id: string;
  description: string;
  pattern: string;
  isRegex: boolean;
  highlightRanges: HighlightRange[];
  conclusion: ParseConclusion;
  nextRules: string[];
  priority: number;
  autoGenerated: boolean;
}

export interface DecisionNode {
  ruleId: string;
  matched: boolean;
  highlights: HighlightRange[];
  conclusion: ParseConclusion;
  children: DecisionNode[];
}

export interface ParseStep {
  stepNumber: number;
  rule: ParsingRule;
  matched: boolean;
  highlights: HighlightRange[];
  cumulativeConclusion: ParseConclusion;
  explanation: string;
}

export interface ParseResult {
  input: string;
  success: boolean;
  conclusion: ParseConclusion;
  steps: ParseStep[];
  decisionTree: DecisionNode;
  matchedForms: MatchedForm[];
}

export interface MatchedForm {
  tableId: string;
  stem: string;
  tense: string;
  personNumberGender: string;
  form: string;
  confidence: number;
}

export interface ParsingRuleSet {
  languageId: string;
  version: string;
  rules: ParsingRule[];
  entryPoints: string[];
  updatedAt: string;
}

export function createEmptyParseResult(input: string): ParseResult {
  return {
    input,
    success: false,
    conclusion: {},
    steps: [],
    decisionTree: {
      ruleId: 'root',
      matched: false,
      highlights: [],
      conclusion: {},
      children: [],
    },
    matchedForms: [],
  };
}

export function mergeConclusions(
  base: ParseConclusion,
  addition: ParseConclusion
): ParseConclusion {
  return {
    ...base,
    ...Object.fromEntries(
      Object.entries(addition).filter(([, v]) => v !== undefined)
    ),
  };
}

export function conclusionToString(conclusion: ParseConclusion): string {
  const parts: string[] = [];
  if (conclusion.stem) parts.push(conclusion.stem);
  if (conclusion.tense) parts.push(conclusion.tense);
  if (conclusion.person) parts.push(conclusion.person);
  if (conclusion.gender) parts.push(conclusion.gender);
  if (conclusion.number) parts.push(conclusion.number);
  return parts.join(' ');
}
