import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { ParsingRuleSet, ParsingRule } from '../types/parsing';
import type { EnrichedParseResult } from '../utils/parsing/parseEngine';

interface ParsingState {
  // Rule sets per language
  ruleSets: Record<string, ParsingRuleSet>;

  // Current parse state
  currentInput: string;
  currentResult: EnrichedParseResult | null;
  isLoading: boolean;
  error: string | null;

  // View mode
  viewMode: 'step-by-step' | 'tree';
  currentStep: number;
  autoPlay: boolean;

  // Settings
  useSedra: boolean;
  useLocalTables: boolean;

  // Parse history
  history: Array<{ input: string; timestamp: number; success: boolean }>;

  // Actions
  setInput: (input: string) => void;
  setResult: (result: EnrichedParseResult | null) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setViewMode: (mode: 'step-by-step' | 'tree') => void;
  setCurrentStep: (step: number) => void;
  nextStep: () => void;
  prevStep: () => void;
  setAutoPlay: (autoPlay: boolean) => void;
  setUseSedra: (use: boolean) => void;
  setUseLocalTables: (use: boolean) => void;

  // Rule management
  setRuleSet: (languageId: string, ruleSet: ParsingRuleSet) => void;
  getRuleSet: (languageId: string) => ParsingRuleSet | null;
  updateRule: (languageId: string, ruleId: string, updates: Partial<ParsingRule>) => void;
  addRule: (languageId: string, rule: ParsingRule) => void;
  deleteRule: (languageId: string, ruleId: string) => void;

  // History
  addToHistory: (input: string, success: boolean) => void;
  clearHistory: () => void;
}

export const useParsingStore = create<ParsingState>()(
  persist(
    (set, get) => ({
      // Initial state
      ruleSets: {},
      currentInput: '',
      currentResult: null,
      isLoading: false,
      error: null,
      viewMode: 'step-by-step',
      currentStep: 0,
      autoPlay: false,
      useSedra: true,
      useLocalTables: true,
      history: [],

      // Input/Result actions
      setInput: (input) => set({ currentInput: input }),
      setResult: (result) => set({ currentResult: result, currentStep: 0 }),
      setLoading: (loading) => set({ isLoading: loading }),
      setError: (error) => set({ error }),

      // View actions
      setViewMode: (mode) => set({ viewMode: mode }),
      setCurrentStep: (step) => set({ currentStep: step }),
      nextStep: () => {
        const { currentResult, currentStep } = get();
        if (currentResult && currentStep < currentResult.steps.length - 1) {
          set({ currentStep: currentStep + 1 });
        }
      },
      prevStep: () => {
        const { currentStep } = get();
        if (currentStep > 0) {
          set({ currentStep: currentStep - 1 });
        }
      },
      setAutoPlay: (autoPlay) => set({ autoPlay }),

      // Settings
      setUseSedra: (use) => set({ useSedra: use }),
      setUseLocalTables: (use) => set({ useLocalTables: use }),

      // Rule management
      setRuleSet: (languageId, ruleSet) =>
        set((state) => ({
          ruleSets: { ...state.ruleSets, [languageId]: ruleSet },
        })),

      getRuleSet: (languageId) => get().ruleSets[languageId] || null,

      updateRule: (languageId, ruleId, updates) =>
        set((state) => {
          const ruleSet = state.ruleSets[languageId];
          if (!ruleSet) return state;

          const updatedRules = ruleSet.rules.map((rule) =>
            rule.id === ruleId ? { ...rule, ...updates, autoGenerated: false } : rule
          );

          return {
            ruleSets: {
              ...state.ruleSets,
              [languageId]: {
                ...ruleSet,
                rules: updatedRules,
                updatedAt: new Date().toISOString(),
              },
            },
          };
        }),

      addRule: (languageId, rule) =>
        set((state) => {
          const ruleSet = state.ruleSets[languageId];
          if (!ruleSet) return state;

          return {
            ruleSets: {
              ...state.ruleSets,
              [languageId]: {
                ...ruleSet,
                rules: [...ruleSet.rules, rule],
                updatedAt: new Date().toISOString(),
              },
            },
          };
        }),

      deleteRule: (languageId, ruleId) =>
        set((state) => {
          const ruleSet = state.ruleSets[languageId];
          if (!ruleSet) return state;

          return {
            ruleSets: {
              ...state.ruleSets,
              [languageId]: {
                ...ruleSet,
                rules: ruleSet.rules.filter((r) => r.id !== ruleId),
                entryPoints: ruleSet.entryPoints.filter((ep) => ep !== ruleId),
                updatedAt: new Date().toISOString(),
              },
            },
          };
        }),

      // History
      addToHistory: (input, success) =>
        set((state) => ({
          history: [
            { input, timestamp: Date.now(), success },
            ...state.history.slice(0, 49), // Keep last 50
          ],
        })),

      clearHistory: () => set({ history: [] }),
    }),
    {
      name: 'lang-helper-parsing',
      partialize: (state) => ({
        ruleSets: state.ruleSets,
        useSedra: state.useSedra,
        useLocalTables: state.useLocalTables,
        history: state.history,
        viewMode: state.viewMode,
      }),
    }
  )
);
