import { useState } from 'react';
import { useParsingStore } from '../../stores/parsingStore';
import { useLanguageStore } from '../../stores/languageStore';
import type { ParsingRule, ParseConclusion } from '../../types/parsing';

interface RuleEditorProps {
  onClose?: () => void;
}

export function RuleEditor({ onClose }: RuleEditorProps) {
  const { getCurrentLanguage } = useLanguageStore();
  const currentLang = getCurrentLanguage();
  const { getRuleSet, updateRule, addRule, deleteRule, setRuleSet } = useParsingStore();

  const ruleSet = currentLang ? getRuleSet(currentLang.id) : null;
  const [selectedRuleId, setSelectedRuleId] = useState<string | null>(null);
  const [editingRule, setEditingRule] = useState<ParsingRule | null>(null);
  const [isCreating, setIsCreating] = useState(false);

  const handleSelectRule = (rule: ParsingRule) => {
    setSelectedRuleId(rule.id);
    setEditingRule({ ...rule });
    setIsCreating(false);
  };

  const handleCreateNew = () => {
    setIsCreating(true);
    setSelectedRuleId(null);
    setEditingRule({
      id: `custom_${Date.now()}`,
      description: '',
      pattern: '',
      isRegex: true,
      highlightRanges: [],
      conclusion: {},
      nextRules: [],
      priority: ruleSet?.rules.length || 0,
      autoGenerated: false,
    });
  };

  const handleSave = () => {
    if (!editingRule || !currentLang) return;

    if (isCreating) {
      addRule(currentLang.id, editingRule);
    } else {
      updateRule(currentLang.id, editingRule.id, editingRule);
    }

    setSelectedRuleId(editingRule.id);
    setIsCreating(false);
  };

  const handleDelete = () => {
    if (!selectedRuleId || !currentLang) return;
    if (confirm('Are you sure you want to delete this rule?')) {
      deleteRule(currentLang.id, selectedRuleId);
      setSelectedRuleId(null);
      setEditingRule(null);
    }
  };

  const handleExport = () => {
    if (!ruleSet) return;
    const blob = new Blob([JSON.stringify(ruleSet, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentLang?.id || 'rules'}-parsing-rules.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !currentLang) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const imported = JSON.parse(event.target?.result as string);
        if (imported.rules && Array.isArray(imported.rules)) {
          setRuleSet(currentLang.id, imported);
        }
      } catch (err) {
        alert('Invalid JSON file');
      }
    };
    reader.readAsText(file);
    e.target.value = '';
  };

  const updateConclusion = (key: keyof ParseConclusion, value: string) => {
    if (!editingRule) return;
    setEditingRule({
      ...editingRule,
      conclusion: {
        ...editingRule.conclusion,
        [key]: value || undefined,
      },
    });
  };

  if (!currentLang) {
    return (
      <div className="text-center text-gray-500 dark:text-gray-400 py-8">
        Select a language first
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with actions */}
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">
          Parsing Rules ({currentLang.name})
        </h2>
        <div className="flex gap-2">
          <button
            onClick={handleCreateNew}
            className="px-3 py-1 bg-green-600 text-white text-sm rounded hover:bg-green-700 transition-colors"
          >
            + New Rule
          </button>
          <button
            onClick={handleExport}
            className="px-3 py-1 bg-gray-600 text-white text-sm rounded hover:bg-gray-700 transition-colors"
          >
            Export
          </button>
          <label className="px-3 py-1 bg-gray-600 text-white text-sm rounded hover:bg-gray-700 transition-colors cursor-pointer">
            Import
            <input type="file" accept=".json" onChange={handleImport} className="hidden" />
          </label>
          {onClose && (
            <button
              onClick={onClose}
              className="px-3 py-1 bg-gray-400 text-white text-sm rounded hover:bg-gray-500 transition-colors"
            >
              Close
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Rule list */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow max-h-[600px] overflow-auto">
          <div className="sticky top-0 bg-gray-100 dark:bg-gray-700 px-4 py-2 border-b border-gray-200 dark:border-gray-600">
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
              {ruleSet?.rules.length || 0} rules
            </span>
          </div>

          {ruleSet?.rules.map((rule) => (
            <div
              key={rule.id}
              onClick={() => handleSelectRule(rule)}
              className={`p-3 border-b border-gray-200 dark:border-gray-700 cursor-pointer transition-colors ${
                selectedRuleId === rule.id
                  ? 'bg-blue-50 dark:bg-blue-900/30'
                  : 'hover:bg-gray-50 dark:hover:bg-gray-700'
              }`}
            >
              <div className="flex items-center gap-2">
                <span className={`text-xs px-1.5 py-0.5 rounded ${
                  rule.autoGenerated
                    ? 'bg-gray-200 dark:bg-gray-600 text-gray-600 dark:text-gray-300'
                    : 'bg-blue-200 dark:bg-blue-700 text-blue-700 dark:text-blue-200'
                }`}>
                  {rule.autoGenerated ? 'Auto' : 'Custom'}
                </span>
                <span className="font-mono text-sm text-gray-900 dark:text-white truncate">
                  {rule.id}
                </span>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400 mt-1 truncate">
                {rule.description || rule.pattern}
              </div>
            </div>
          ))}

          {(!ruleSet || ruleSet.rules.length === 0) && (
            <div className="p-8 text-center text-gray-500 dark:text-gray-400">
              No rules yet. Import verb tables to auto-generate rules, or create custom rules.
            </div>
          )}
        </div>

        {/* Rule editor form */}
        {editingRule && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 space-y-4">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white">
              {isCreating ? 'Create New Rule' : 'Edit Rule'}
            </h3>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Rule ID
              </label>
              <input
                type="text"
                value={editingRule.id}
                onChange={(e) => setEditingRule({ ...editingRule, id: e.target.value })}
                disabled={!isCreating}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:bg-gray-100 dark:disabled:bg-gray-800"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Description
              </label>
              <input
                type="text"
                value={editingRule.description}
                onChange={(e) => setEditingRule({ ...editingRule, description: e.target.value })}
                placeholder="What does this rule detect?"
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Pattern (Regex)
              </label>
              <input
                type="text"
                value={editingRule.pattern}
                onChange={(e) => setEditingRule({ ...editingRule, pattern: e.target.value })}
                placeholder="e.g., ܰܬ$ for suffix"
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white font-mono"
                dir="ltr"
              />
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Use ^ for prefix, $ for suffix, e.g., "^ܢ" matches prefix nun
              </p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Person
                </label>
                <select
                  value={editingRule.conclusion.person || ''}
                  onChange={(e) => updateConclusion('person', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="">—</option>
                  <option value="1st">1st</option>
                  <option value="2nd">2nd</option>
                  <option value="3rd">3rd</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Number
                </label>
                <select
                  value={editingRule.conclusion.number || ''}
                  onChange={(e) => updateConclusion('number', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="">—</option>
                  <option value="singular">Singular</option>
                  <option value="plural">Plural</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Gender
                </label>
                <select
                  value={editingRule.conclusion.gender || ''}
                  onChange={(e) => updateConclusion('gender', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="">—</option>
                  <option value="masculine">Masculine</option>
                  <option value="feminine">Feminine</option>
                  <option value="common">Common</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Tense
                </label>
                <select
                  value={editingRule.conclusion.tense || ''}
                  onChange={(e) => updateConclusion('tense', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="">—</option>
                  <option value="past">Past (Perfect)</option>
                  <option value="future">Future (Imperfect)</option>
                  <option value="imperative">Imperative</option>
                  <option value="infinitive">Infinitive</option>
                  <option value="active-participle">Active Participle</option>
                  <option value="passive-participle">Passive Participle</option>
                </select>
              </div>

              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Stem
                </label>
                <select
                  value={editingRule.conclusion.stem || ''}
                  onChange={(e) => updateConclusion('stem', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="">—</option>
                  <option value="peal">Peal</option>
                  <option value="pael">Pael</option>
                  <option value="aphel">Aphel</option>
                  <option value="ethpeel">Ethpeel</option>
                  <option value="ethpaal">Ethpaal</option>
                  <option value="ettaphal">Ettaphal</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Priority
              </label>
              <input
                type="number"
                value={editingRule.priority}
                onChange={(e) => setEditingRule({ ...editingRule, priority: parseInt(e.target.value) || 0 })}
                className="w-24 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Lower numbers are checked first
              </p>
            </div>

            <div className="flex gap-2 pt-4 border-t border-gray-200 dark:border-gray-700">
              <button
                onClick={handleSave}
                className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
              >
                {isCreating ? 'Create Rule' : 'Save Changes'}
              </button>
              {!isCreating && (
                <button
                  onClick={handleDelete}
                  className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 transition-colors"
                >
                  Delete
                </button>
              )}
              <button
                onClick={() => {
                  setEditingRule(null);
                  setSelectedRuleId(null);
                  setIsCreating(false);
                }}
                className="px-4 py-2 bg-gray-300 dark:bg-gray-600 text-gray-700 dark:text-white rounded hover:bg-gray-400 dark:hover:bg-gray-500 transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {!editingRule && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 flex items-center justify-center text-gray-500 dark:text-gray-400">
            Select a rule to edit or create a new one
          </div>
        )}
      </div>
    </div>
  );
}
