// Built-in morphological parsing rules for Syriac
// These work without requiring verb tables

import type { ParsingRule, ParsingRuleSet } from '../../types/parsing';

// Common Syriac verb suffixes (perfect/past tense)
const SYRIAC_PERFECT_SUFFIXES: ParsingRule[] = [
  {
    id: 'syr_perf_3ms',
    description: 'No suffix - 3rd masculine singular perfect',
    pattern: '^[ܐ-ܬ][ܰܳܶܺܽ]?[ܐ-ܬ][ܰܳܶܺܽ]?[ܐ-ܬ]$',
    isRegex: true,
    highlightRanges: [],
    conclusion: { person: '3rd', gender: 'masculine', number: 'singular', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 100,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_3fs',
    description: 'Suffix ܬ݂/ܰܬ - 3rd feminine singular perfect',
    pattern: '[ܰܳ]ܬ݂?$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: '3fs suffix' }],
    conclusion: { person: '3rd', gender: 'feminine', number: 'singular', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 10,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_2ms',
    description: 'Suffix ܬ - 2nd masculine singular perfect',
    pattern: '[ܶܰ]ܬ$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: '2ms suffix' }],
    conclusion: { person: '2nd', gender: 'masculine', number: 'singular', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 11,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_2fs',
    description: 'Suffix ܬܝ - 2nd feminine singular perfect',
    pattern: 'ܬܝ$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: '2fs suffix' }],
    conclusion: { person: '2nd', gender: 'feminine', number: 'singular', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 12,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_1s',
    description: 'Suffix ܬ/ܶܬ - 1st singular perfect',
    pattern: '[ܶܺ]ܬ$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: '1s suffix' }],
    conclusion: { person: '1st', number: 'singular', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 13,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_3mp',
    description: 'Suffix ܘ - 3rd masculine plural perfect',
    pattern: '[ܰܳ]ܘ$',
    isRegex: true,
    highlightRanges: [{ start: -1, end: 0, type: 'affix', label: '3mp suffix' }],
    conclusion: { person: '3rd', gender: 'masculine', number: 'plural', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 14,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_3fp',
    description: 'Suffix ܝ̈/ܝ - 3rd feminine plural perfect',
    pattern: '[̈ܝ]$',
    isRegex: true,
    highlightRanges: [{ start: -1, end: 0, type: 'affix', label: '3fp suffix' }],
    conclusion: { person: '3rd', gender: 'feminine', number: 'plural', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 15,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_2mp',
    description: 'Suffix ܬܘܢ - 2nd masculine plural perfect',
    pattern: 'ܬܘܢ$',
    isRegex: true,
    highlightRanges: [{ start: -3, end: 0, type: 'affix', label: '2mp suffix' }],
    conclusion: { person: '2nd', gender: 'masculine', number: 'plural', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 5,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_2fp',
    description: 'Suffix ܬܝܢ - 2nd feminine plural perfect',
    pattern: 'ܬܝܢ$',
    isRegex: true,
    highlightRanges: [{ start: -3, end: 0, type: 'affix', label: '2fp suffix' }],
    conclusion: { person: '2nd', gender: 'feminine', number: 'plural', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 6,
    autoGenerated: false,
  },
  {
    id: 'syr_perf_1p',
    description: 'Suffix ܢ/ܢܢ - 1st plural perfect',
    pattern: 'ܢܢ?$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: '1p suffix' }],
    conclusion: { person: '1st', number: 'plural', tense: 'past' },
    nextRules: ['syr_stem_peal', 'syr_stem_pael', 'syr_stem_aphel'],
    priority: 16,
    autoGenerated: false,
  },
];

// Syriac imperfect/future prefixes
const SYRIAC_IMPERFECT_PREFIXES: ParsingRule[] = [
  {
    id: 'syr_impf_3ms',
    description: 'Prefix ܢ - 3rd masculine singular imperfect',
    pattern: '^ܢ[ܶܺ]?',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: '3ms prefix' }],
    conclusion: { person: '3rd', gender: 'masculine', number: 'singular', tense: 'future' },
    nextRules: ['syr_impf_suffix_none', 'syr_impf_suffix_waw'],
    priority: 20,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_3fs',
    description: 'Prefix ܬ - 3rd feminine singular imperfect',
    pattern: '^ܬ[ܶܺ]?',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: '3fs prefix' }],
    conclusion: { person: '3rd', gender: 'feminine', number: 'singular', tense: 'future' },
    nextRules: ['syr_impf_suffix_none'],
    priority: 21,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_2ms',
    description: 'Prefix ܬ - 2nd masculine singular imperfect',
    pattern: '^ܬ[ܶܺ]?',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: '2ms prefix' }],
    conclusion: { person: '2nd', gender: 'masculine', number: 'singular', tense: 'future' },
    nextRules: ['syr_impf_suffix_none'],
    priority: 22,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_2fs',
    description: 'Prefix ܬ with suffix ܝܢ - 2nd feminine singular imperfect',
    pattern: '^ܬ.*ܝܢ$',
    isRegex: true,
    highlightRanges: [
      { start: 0, end: 1, type: 'affix', label: '2fs prefix' },
      { start: -2, end: 0, type: 'affix', label: '2fs suffix' },
    ],
    conclusion: { person: '2nd', gender: 'feminine', number: 'singular', tense: 'future' },
    nextRules: [],
    priority: 7,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_1s',
    description: 'Prefix ܐ - 1st singular imperfect',
    pattern: '^ܐ[ܶܺ]?',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: '1s prefix' }],
    conclusion: { person: '1st', number: 'singular', tense: 'future' },
    nextRules: ['syr_impf_suffix_none'],
    priority: 23,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_3mp',
    description: 'Prefix ܢ with suffix ܘܢ - 3rd masculine plural imperfect',
    pattern: '^ܢ.*ܘܢ$',
    isRegex: true,
    highlightRanges: [
      { start: 0, end: 1, type: 'affix', label: '3mp prefix' },
      { start: -2, end: 0, type: 'affix', label: '3mp suffix' },
    ],
    conclusion: { person: '3rd', gender: 'masculine', number: 'plural', tense: 'future' },
    nextRules: [],
    priority: 8,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_1p',
    description: 'Prefix ܢ - 1st plural imperfect',
    pattern: '^ܢ[ܶܺ]?',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: '1p prefix' }],
    conclusion: { person: '1st', number: 'plural', tense: 'future' },
    nextRules: ['syr_impf_suffix_none'],
    priority: 24,
    autoGenerated: false,
  },
];

// Stem identification rules
const SYRIAC_STEM_RULES: ParsingRule[] = [
  {
    id: 'syr_stem_peal',
    description: 'Peal stem (G-stem) - simple active',
    pattern: '^[^ܐܡܬ]',
    isRegex: true,
    highlightRanges: [],
    conclusion: { stem: 'peal' },
    nextRules: [],
    priority: 50,
    autoGenerated: false,
  },
  {
    id: 'syr_stem_pael',
    description: 'Pael stem (D-stem) - intensive, with doubled middle radical',
    pattern: '.*',
    isRegex: true,
    highlightRanges: [],
    conclusion: { stem: 'pael' },
    nextRules: [],
    priority: 51,
    autoGenerated: false,
  },
  {
    id: 'syr_stem_aphel',
    description: 'Aphel stem (C-stem) - causative, prefix ܐ',
    pattern: '^ܐ',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 1, type: 'affix', label: 'aphel prefix' }],
    conclusion: { stem: 'aphel' },
    nextRules: [],
    priority: 40,
    autoGenerated: false,
  },
  {
    id: 'syr_stem_ethpeel',
    description: 'Ethpeel stem (Gt-stem) - passive/reflexive of Peal',
    pattern: '^ܐܬ',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 2, type: 'affix', label: 'ethpeel prefix' }],
    conclusion: { stem: 'ethpeel' },
    nextRules: [],
    priority: 30,
    autoGenerated: false,
  },
  {
    id: 'syr_stem_ethpaal',
    description: 'Ethpaal stem (Dt-stem) - passive/reflexive of Pael',
    pattern: '^ܐܬ',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 2, type: 'affix', label: 'ethpaal prefix' }],
    conclusion: { stem: 'ethpaal' },
    nextRules: [],
    priority: 31,
    autoGenerated: false,
  },
  {
    id: 'syr_stem_ettaphal',
    description: 'Ettaphal stem (Ct-stem) - passive of Aphel',
    pattern: '^ܐܬ',
    isRegex: true,
    highlightRanges: [{ start: 0, end: 2, type: 'affix', label: 'ettaphal prefix' }],
    conclusion: { stem: 'ettaphal' },
    nextRules: [],
    priority: 32,
    autoGenerated: false,
  },
];

// Participle rules
const SYRIAC_PARTICIPLE_RULES: ParsingRule[] = [
  {
    id: 'syr_act_ptc_ms',
    description: 'Active participle masculine singular - pattern qāṭel',
    pattern: '^[ܐ-ܬ][ܳ][ܐ-ܬ][ܶ][ܐ-ܬ]$',
    isRegex: true,
    highlightRanges: [],
    conclusion: { tense: 'active-participle', gender: 'masculine', number: 'singular' },
    nextRules: ['syr_stem_peal'],
    priority: 25,
    autoGenerated: false,
  },
  {
    id: 'syr_pass_ptc_ms',
    description: 'Passive participle masculine singular - pattern qṭīl',
    pattern: '^[ܐ-ܬ][ܺ][ܐ-ܬ][ܺܝ][ܐ-ܬ]$',
    isRegex: true,
    highlightRanges: [],
    conclusion: { tense: 'passive-participle', gender: 'masculine', number: 'singular' },
    nextRules: ['syr_stem_peal'],
    priority: 26,
    autoGenerated: false,
  },
];

// Imperfect suffixes
const SYRIAC_IMPERFECT_SUFFIXES: ParsingRule[] = [
  {
    id: 'syr_impf_suffix_none',
    description: 'No imperfect suffix',
    pattern: '[ܘܠ]$',
    isRegex: true,
    highlightRanges: [],
    conclusion: {},
    nextRules: [],
    priority: 60,
    autoGenerated: false,
  },
  {
    id: 'syr_impf_suffix_waw',
    description: 'Suffix ܘܢ - plural marker',
    pattern: 'ܘܢ$',
    isRegex: true,
    highlightRanges: [{ start: -2, end: 0, type: 'affix', label: 'plural suffix' }],
    conclusion: { number: 'plural' },
    nextRules: [],
    priority: 9,
    autoGenerated: false,
  },
];

// Combine all rules
const ALL_BUILTIN_RULES: ParsingRule[] = [
  ...SYRIAC_IMPERFECT_PREFIXES,
  ...SYRIAC_PERFECT_SUFFIXES,
  ...SYRIAC_STEM_RULES,
  ...SYRIAC_PARTICIPLE_RULES,
  ...SYRIAC_IMPERFECT_SUFFIXES,
];

// Entry points - start with prefix checks, then suffix checks
const ENTRY_POINTS = [
  // Imperfect (has prefixes)
  'syr_impf_3ms',
  'syr_impf_3fs',
  'syr_impf_2ms',
  'syr_impf_2fs',
  'syr_impf_1s',
  'syr_impf_3mp',
  'syr_impf_1p',
  // Stems with prefix markers
  'syr_stem_ethpeel',
  'syr_stem_ethpaal',
  'syr_stem_ettaphal',
  'syr_stem_aphel',
  // Perfect (suffix-based)
  'syr_perf_2mp',
  'syr_perf_2fp',
  'syr_perf_3fs',
  'syr_perf_2ms',
  'syr_perf_2fs',
  'syr_perf_1s',
  'syr_perf_3mp',
  'syr_perf_3fp',
  'syr_perf_1p',
  // Participles
  'syr_act_ptc_ms',
  'syr_pass_ptc_ms',
];

export function getBuiltinSyriacRules(): ParsingRuleSet {
  return {
    languageId: 'syriac',
    version: '1.0.0-builtin',
    rules: ALL_BUILTIN_RULES,
    entryPoints: ENTRY_POINTS,
    updatedAt: new Date().toISOString(),
  };
}

export function getBuiltinRulesForLanguage(languageId: string): ParsingRuleSet | null {
  if (languageId === 'syriac') {
    return getBuiltinSyriacRules();
  }
  // Add Hebrew, Aramaic, etc. rules here in the future
  return null;
}
