import type {
  ParsingRule,
  ParsingRuleSet,
  ParseResult,
  DecisionNode,
  HighlightRange,
} from '../../types/parsing';
import { createEmptyParseResult, mergeConclusions } from '../../types/parsing';
import type { VerbTable } from '../../types/verb';
import { findExactMatches } from './ruleGenerator';
import { lookupWord, lookupLexeme, fetchLexemeParadigmHtml, mapSedraToConclusion, getGloss, type SedraWord, type SedraLexeme } from '../../services/sedraApi';
import { parseSedraParadigmHtml, type SedraParadigm } from '../sedraParadigm';
import { reverseInflectionLookup, type RankedParadigmMatch } from './reverseInflection';

export interface ParseOptions {
  useSedra: boolean;
  useLocalTables: boolean;
  maxSteps: number;
}

const DEFAULT_OPTIONS: ParseOptions = {
  useSedra: true,
  useLocalTables: true,
  maxSteps: 20,
};

export interface EnrichedParseResult extends ParseResult {
  sedraResults?: SedraWord[];
  sedraGloss?: string;
  sedraLexeme?: SedraLexeme;
  sedraParadigm?: SedraParadigm;
  reverseInflectionUsed?: boolean;
  reverseInflectionRoot?: string;
  rankedParadigmMatches?: RankedParadigmMatch[];
}

// Main parsing function
export async function parseForm(
  input: string,
  ruleSet: ParsingRuleSet | null,
  tables: VerbTable[],
  options: Partial<ParseOptions> = {}
): Promise<EnrichedParseResult> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const result: EnrichedParseResult = {
    ...createEmptyParseResult(input),
    sedraResults: [],
  };

  // 1. Look up in SEDRA API (if enabled)
  if (opts.useSedra) {
    const sedraResults = await lookupWord(input);
    result.sedraResults = sedraResults;

    if (sedraResults.length > 0) {
      // Use first SEDRA result for primary conclusion
      const primaryResult = sedraResults[0];
      const sedraConclusion = mapSedraToConclusion(primaryResult);
      result.conclusion = mergeConclusions(result.conclusion, sedraConclusion);
      result.sedraGloss = getGloss(primaryResult);
      result.success = true;

      // Add SEDRA as a parse step
      result.steps.push({
        stepNumber: 1,
        rule: {
          id: 'sedra_lookup',
          description: 'SEDRA API lookup',
          pattern: input,
          isRegex: false,
          highlightRanges: [],
          conclusion: sedraConclusion,
          nextRules: [],
          priority: 0,
          autoGenerated: false,
        },
        matched: true,
        highlights: [],
        cumulativeConclusion: sedraConclusion,
        explanation: `SEDRA found: ${formatSedraResult(primaryResult)}`,
      });

      // Try to fetch the lexeme and full paradigm
      if (primaryResult.lexeme?.id) {
        try {
          const lexeme = await lookupLexeme(primaryResult.lexeme.id);
          if (lexeme) {
            result.sedraLexeme = lexeme;

            // If it's a verb, try to get the full paradigm
            if (lexeme.categoryType === 'verb' || primaryResult.kaylo) {
              const paradigmHtml = await fetchLexemeParadigmHtml(primaryResult.lexeme.id);
              if (paradigmHtml) {
                const paradigm = parseSedraParadigmHtml(paradigmHtml, primaryResult.lexeme.id);
                if (paradigm) {
                  result.sedraParadigm = paradigm;
                }
              }
            }
          }
        } catch (e) {
          console.error('Failed to fetch lexeme/paradigm:', e);
        }
      }
    }
  }

  // 1.5 Reverse inflection: strip affixes to find root in SEDRA
  if (opts.useSedra && result.sedraResults?.length === 0) {
    try {
      const reverseResult = await reverseInflectionLookup(input);
      if (reverseResult) {
        result.sedraResults = reverseResult.sedraWords;
        result.sedraLexeme = reverseResult.lexeme ?? undefined;
        result.sedraParadigm = reverseResult.paradigm ?? undefined;
        result.sedraGloss = reverseResult.gloss;

        // Use the candidate's implied conclusion
        const implied = reverseResult.candidate.impliedConclusions[0] ?? {};
        result.conclusion = mergeConclusions(result.conclusion, implied);
        if (reverseResult.candidate.consonants) {
          result.conclusion = mergeConclusions(result.conclusion, { root: reverseResult.candidate.consonants });
        }
        result.success = true;
        result.reverseInflectionUsed = true;
        result.reverseInflectionRoot = reverseResult.candidate.consonants;
        result.rankedParadigmMatches = reverseResult.rankedMatches;

        // Use best paradigm match to refine the conclusion
        if (reverseResult.rankedMatches.length > 0) {
          const best = reverseResult.rankedMatches[0].form;
          result.conclusion = mergeConclusions(result.conclusion, {
            stem: best.stem,
            tense: best.tense,
          });
        }

        // Add reverse inflection steps
        for (const step of reverseResult.steps) {
          step.stepNumber = result.steps.length + step.stepNumber;
          result.steps.push(step);
        }
      }
    } catch (e) {
      console.error('Reverse inflection error:', e);
    }
  }

  // 2. Search local tables for exact matches
  if (opts.useLocalTables && tables.length > 0) {
    const tableMatches = findExactMatches(input, tables);

    for (const match of tableMatches) {
      result.matchedForms.push({
        tableId: match.table.id,
        stem: match.stem,
        tense: match.tense,
        personNumberGender: match.png,
        form: match.form.form,
        confidence: match.form.form === input ? 1.0 : 0.8,
      });

      // Add segments as highlights if available
      if (match.form.segments) {
        const highlights = segmentsToHighlights(match.form.segments);
        if (highlights.length > 0) {
          result.steps.push({
            stepNumber: result.steps.length + 1,
            rule: {
              id: `table_match_${match.table.id}`,
              description: `Matched in ${match.table.classDisplayName} table`,
              pattern: match.form.form,
              isRegex: false,
              highlightRanges: highlights,
              conclusion: {
                stem: match.stem,
                tense: match.tense,
                ...parsePNG(match.png),
              },
              nextRules: [],
              priority: 0,
              autoGenerated: false,
            },
            matched: true,
            highlights,
            cumulativeConclusion: result.conclusion,
            explanation: `Found in ${match.stem} ${match.tense}: ${match.png}`,
          });
        }
      }
    }

    if (tableMatches.length > 0 && !result.success) {
      const firstMatch = tableMatches[0];
      result.conclusion = mergeConclusions(result.conclusion, {
        stem: firstMatch.stem,
        tense: firstMatch.tense,
        ...parsePNG(firstMatch.png),
      });
      result.success = true;
    }
  }

  // 3. Apply parsing rules (if available)
  if (ruleSet && ruleSet.rules.length > 0) {
    const ruleResult = applyRules(input, ruleSet, opts.maxSteps);

    // Merge rule-based results
    for (const step of ruleResult.steps) {
      step.stepNumber = result.steps.length + step.stepNumber;
      result.steps.push(step);
    }

    if (ruleResult.success) {
      result.conclusion = mergeConclusions(result.conclusion, ruleResult.conclusion);
      result.success = true;
    }

    result.decisionTree = ruleResult.decisionTree;
  }

  return result;
}

// Apply parsing rules to input
function applyRules(
  input: string,
  ruleSet: ParsingRuleSet,
  maxSteps: number
): ParseResult {
  const result = createEmptyParseResult(input);
  const rulesById = new Map(ruleSet.rules.map(r => [r.id, r]));

  // Build decision tree
  result.decisionTree = buildDecisionTree(input, ruleSet.entryPoints, rulesById, 0);

  // Extract steps from successful path
  const successPath = findSuccessPath(result.decisionTree);
  let stepNumber = 1;

  for (const node of successPath) {
    if (!node.matched) continue;

    const rule = rulesById.get(node.ruleId);
    if (!rule) continue;

    result.conclusion = mergeConclusions(result.conclusion, node.conclusion);

    result.steps.push({
      stepNumber: stepNumber++,
      rule,
      matched: true,
      highlights: node.highlights,
      cumulativeConclusion: { ...result.conclusion },
      explanation: rule.description,
    });

    if (stepNumber > maxSteps) break;
  }

  result.success = result.steps.length > 0;
  return result;
}

// Build decision tree recursively
function buildDecisionTree(
  input: string,
  ruleIds: string[],
  rulesById: Map<string, ParsingRule>,
  depth: number
): DecisionNode {
  const rootNode: DecisionNode = {
    ruleId: 'root',
    matched: false,
    highlights: [],
    conclusion: {},
    children: [],
  };

  if (depth > 10) return rootNode; // Prevent infinite recursion

  for (const ruleId of ruleIds) {
    const rule = rulesById.get(ruleId);
    if (!rule) continue;

    const { matched, highlights } = testRule(input, rule);

    const childNode: DecisionNode = {
      ruleId,
      matched,
      highlights,
      conclusion: matched ? rule.conclusion : {},
      children: [],
    };

    if (matched && rule.nextRules.length > 0) {
      childNode.children = rule.nextRules
        .map(nextId => {
          const nextRule = rulesById.get(nextId);
          if (!nextRule) return null;

          const nextResult = testRule(input, nextRule);
          return {
            ruleId: nextId,
            matched: nextResult.matched,
            highlights: nextResult.highlights,
            conclusion: nextResult.matched ? nextRule.conclusion : {},
            children: [] as DecisionNode[],
          };
        })
        .filter((n): n is DecisionNode => n !== null);
    }

    rootNode.children.push(childNode);
  }

  rootNode.matched = rootNode.children.some(c => c.matched);
  return rootNode;
}

// Test a single rule against input
function testRule(
  input: string,
  rule: ParsingRule
): { matched: boolean; highlights: HighlightRange[] } {
  try {
    if (rule.isRegex) {
      const regex = new RegExp(rule.pattern, 'u');
      const match = input.match(regex);

      if (match) {
        // Calculate actual highlight positions
        const highlights: HighlightRange[] = rule.highlightRanges.map(hr => {
          let start = hr.start;
          let end = hr.end;

          // Handle negative indices (from end)
          if (start < 0) start = input.length + start;
          if (end <= 0) end = input.length + end;

          return { ...hr, start, end };
        });

        return { matched: true, highlights };
      }
    } else {
      if (input.includes(rule.pattern)) {
        const idx = input.indexOf(rule.pattern);
        const highlights: HighlightRange[] = [{
          start: idx,
          end: idx + rule.pattern.length,
          type: 'match',
        }];
        return { matched: true, highlights };
      }
    }
  } catch (e) {
    console.error('Rule test error:', e);
  }

  return { matched: false, highlights: [] };
}

// Find successful path through decision tree
function findSuccessPath(tree: DecisionNode): DecisionNode[] {
  const path: DecisionNode[] = [];

  function traverse(node: DecisionNode): boolean {
    if (node.matched) {
      path.push(node);

      // Look for matched children
      for (const child of node.children) {
        if (traverse(child)) return true;
      }

      return true;
    }
    return false;
  }

  for (const child of tree.children) {
    if (traverse(child)) break;
  }

  return path;
}

// Convert segments to highlight ranges
function segmentsToHighlights(
  segments: Array<{ text: string; type: string }>
): HighlightRange[] {
  const highlights: HighlightRange[] = [];
  let position = 0;

  for (const seg of segments) {
    const highlightType = seg.type === 'root' ? 'root' :
      seg.type === 'prefix' || seg.type === 'suffix' ? 'affix' :
        'match';

    highlights.push({
      start: position,
      end: position + seg.text.length,
      type: highlightType,
      label: seg.type,
    });

    position += seg.text.length;
  }

  return highlights;
}

// Parse person-number-gender string
function parsePNG(png: string): { person?: string; gender?: string; number?: string } {
  const result: { person?: string; gender?: string; number?: string } = {};

  const personMatch = png.match(/^(\d)/);
  if (personMatch) {
    result.person = personMatch[1] === '1' ? '1st' :
      personMatch[1] === '2' ? '2nd' :
        personMatch[1] === '3' ? '3rd' : undefined;
  }

  if (png.includes('m')) result.gender = 'masculine';
  else if (png.includes('f')) result.gender = 'feminine';
  else if (png.includes('c')) result.gender = 'common';

  if (png.includes('s')) result.number = 'singular';
  else if (png.includes('p')) result.number = 'plural';

  return result;
}

// Format SEDRA result for display
function formatSedraResult(word: SedraWord): string {
  const parts: string[] = [];

  if (word.kaylo) parts.push(word.kaylo);
  if (word.tense) parts.push(word.tense);
  if (word.person) parts.push(word.person);
  if (word.gender) parts.push(word.gender);
  if (word.number) parts.push(word.number);

  const gloss = getGloss(word);
  if (gloss) parts.push(`"${gloss}"`);

  return parts.join(' ');
}
